/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoyd;

import Funciones.FuncionArchivar;
import Funciones.Medicamento;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class AgregarMedicamento extends javax.swing.JFrame {

    Medicamento medicamento;
    ArrayList<Medicamento> listamedicamentos;
    FuncionArchivar archivo;
    String ruta;
    int medicamentonum = 0;
    boolean bandera=false; 

    public AgregarMedicamento() {
        initComponents();
        archivo = new FuncionArchivar();
        setLocationRelativeTo(null);
        

    }

    public AgregarMedicamento(String ruta) {
        this.ruta = ruta;
        initComponents();
        archivo = new FuncionArchivar();
        setLocationRelativeTo(null);
        traerDatos();
    }

    public void traerDatos() {
        listamedicamentos = null;
        if (true == archivo.existenciaArchivo(ruta)) {
            try {
                listamedicamentos = archivo.mostarArchivoDatosMedicamento(ruta);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AgregarMedicamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void agregarMedicamento(String nombremedicamento, String fechacaducidad, boolean estado, int cantidad, String nota) {
        if (listamedicamentos == null) {
            listamedicamentos = new ArrayList<Medicamento>();
        }
        medicamento = new Medicamento();
        medicamento.setNombremed(nombremedicamento);
        medicamento.setFechacad(fechacaducidad);
        medicamento.setTipo(estado);
        medicamento.setCantidadrestante(cantidad);
        medicamento.setNota(nota);
        listamedicamentos.add(medicamento);
        archivo.escribirArchivo(ruta, listamedicamentos);
        NombreMed.setText(null);
        Nota.setText(null);
        cantidadsobrant.setText(null);
        fechaCad.setText(null);

        listamedicamentos = null;
        

    }

    public AgregarMedicamento(int medicamentonum) {
        initComponents();
        archivo = new FuncionArchivar();
        setLocationRelativeTo(null);
        traerDatos();

    }

    public void modificarMedicamentopreparando(int medicamentonum) {
        this.medicamentonum = medicamentonum;
        NombreMed.setEnabled(false);
        Nota.setEnabled(false);
        fechaCad.setEnabled(false);
        traerDatos();
        if (listamedicamentos == null) {
            JOptionPane.showMessageDialog(null, "No hay registros");
        } else {
            medicamento = listamedicamentos.get(medicamentonum);
            NombreMed.setText(medicamento.getNombremed());
            Nota.setText(medicamento.getNota());
            cantidadsobrant.setText(null);
            fechaCad.setText(medicamento.getFechacad());
            Agregmed.setText("Modificar");
bandera=true;
        }
    }

    public void modificarMedicamento(String nombremedicamento, String fechacaducidad, boolean estado, int cantidad, String nota) {
         medicamento = new Medicamento();
        medicamento.setNombremed(nombremedicamento);
        medicamento.setFechacad(fechacaducidad);
        medicamento.setTipo(estado);
        medicamento.setCantidadrestante(cantidad);
        medicamento.setNota(nota);
        listamedicamentos.set(medicamentonum, medicamento);
        medicamentonum = 0;
        listamedicamentos.add(medicamento);
         archivo.escribirArchivo(ruta, listamedicamentos);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        NombreMed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fechaCad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadsobrant = new javax.swing.JTextField();
        pastillas = new javax.swing.JRadioButton();
        jarabe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Agregmed = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Nota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        NombreMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreMedActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Medicamento");

        fechaCad.setToolTipText("hola");
        fechaCad.setToolTipText("");
        fechaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCadActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de caducidad");

        jLabel3.setText("Tipo de Medicamento");

        cantidadsobrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadsobrantActionPerformed(evt);
            }
        });

        buttonGroup2.add(pastillas);
        pastillas.setText("Pastillas");
        pastillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastillasActionPerformed(evt);
            }
        });

        buttonGroup2.add(jarabe);
        jarabe.setText("Jarabe");
        jarabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarabeActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad sobrante");

        Agregmed.setText("Agregar");
        Agregmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregmedActionPerformed(evt);
            }
        });

        cerrar.setText("x");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nota");

        Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregmed)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreMed, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pastillas)
                                .addGap(18, 18, 18)
                                .addComponent(jarabe))
                            .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadsobrant, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pastillas)
                    .addComponent(jarabe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadsobrant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Agregmed)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreMedActionPerformed

    }//GEN-LAST:event_NombreMedActionPerformed

    private void pastillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastillasActionPerformed

    }//GEN-LAST:event_pastillasActionPerformed

    private void fechaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCadActionPerformed

    }//GEN-LAST:event_fechaCadActionPerformed

    private void cantidadsobrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadsobrantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadsobrantActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void AgregmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregmedActionPerformed
if(bandera!=true){
        traerDatos();
        agregarMedicamento(NombreMed.getText(), fechaCad.getText(), false, Integer.parseInt(cantidadsobrant.getText()), Nota.getText());
}else{
    modificarMedicamento(NombreMed.getText(), fechaCad.getText(), false, Integer.parseInt(cantidadsobrant.getText()), Nota.getText());

}

dispose();

    }//GEN-LAST:event_AgregmedActionPerformed

    private void jarabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarabeActionPerformed


    }//GEN-LAST:event_jarabeActionPerformed

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed

    }//GEN-LAST:event_NotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregmed;
    private javax.swing.JTextField NombreMed;
    private javax.swing.JTextField Nota;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cantidadsobrant;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField fechaCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jarabe;
    private javax.swing.JRadioButton pastillas;
    // End of variables declaration//GEN-END:variables
}
