/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoyd;

import Funciones.DatosUser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Funciones.FuncionArchivar;
import Funciones.FuncionValidar;

/**
 *
 * @author TheSk
 */
public class Agregar extends javax.swing.JFrame {

    
    
    
    String ruta = "usuarios";
    private static IniciarSesion iniciar;
    FuncionArchivar archivo;
    DatosUser datos;
    ArrayList<DatosUser> listausuarios;
    FuncionValidar validar;

    public Agregar() {
        initComponents();
        listausuarios = new ArrayList<DatosUser>();
        archivo = new FuncionArchivar();
        setLocationRelativeTo(null);
        traerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void escribirDatos(String usuario, char[] contra, String pregsecret, String respsecret) {
        if(listausuarios==null){
        listausuarios = new ArrayList<DatosUser>();
        }
        datos = new DatosUser(usuario, contra, pregsecret, respsecret);
        listausuarios.add(datos);
        archivo.escribirArchivo(ruta, listausuarios);
        listausuarios = null;
    
    }

    public void traerDatos() {
        listausuarios = null;
        if (true == archivo.existenciaArchivo(ruta)) {
            try {
                listausuarios = archivo.mostarArchivoDatosMedicamento(ruta);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblNewUsu = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        txtNewUsu = new javax.swing.JTextField();
        ComboBoxPregSecret = new javax.swing.JComboBox<>();
        txtRespSecret = new javax.swing.JTextField();
        btnGuardarU = new javax.swing.JButton();
        btnCancelarU = new javax.swing.JButton();
        NewPassword = new javax.swing.JPasswordField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNewUsu.setText("CREA UN NICKNAME");

        lblNewPass.setText("CREA UNA CONTRASEÑA");

        ComboBoxPregSecret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿El nombre de tu mascota?", "¿Pelicula favorita?", "¿Libro favorito?", "¿Nombre de tu primer maestro?", "¿Marca de ropa favorita?", " ", " " }));

        btnGuardarU.setText("GUARDAR");
        btnGuardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUActionPerformed(evt);
            }
        });

        btnCancelarU.setText("CANCELAR");
        btnCancelarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(NewPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxPregSecret, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRespSecret, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnGuardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnCancelarU)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewUsu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ComboBoxPregSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRespSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarU)
                    .addComponent(btnCancelarU))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUActionPerformed
        // TODO add your handling code here:
        validar = new FuncionValidar();
        try {
            iniciar = new IniciarSesion();
            // Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();
            //  String nombre = txtNewUsu.getText();
            // String contra = CONTRA.getText();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (validar.validarletras(txtNewUsu.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Porfavor ingresa los datos correctamente.");

            //this.setVisible(true); 
        } else {

            escribirDatos(txtNewUsu.getText(), NewPassword.getPassword(), txtRespSecret.getText(), ComboBoxPregSecret.getSelectedItem().toString());
            iniciar.setVisible(true);

            // menu.setLocation((pantallaTamano.width/2)-(menu.getWidth()/2), (pantallaTamano.height/2)-(menu.getHeight()/2));
            //this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnGuardarUActionPerformed

    private void btnCancelarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUActionPerformed
      
        iniciar.setVisible(true);
        
        dispose();
      
    }//GEN-LAST:event_btnCancelarUActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPregSecret;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JButton btnCancelarU;
    private javax.swing.JButton btnGuardarU;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewUsu;
    private javax.swing.JTextField txtNewUsu;
    private javax.swing.JTextField txtRespSecret;
    // End of variables declaration//GEN-END:variables
}
